receivers:
  otlp:
    protocols:
      grpc:
        endpoint: jaeger:4317

processors:
  batch:

exporters:
  otlp:
    #endpoint: xxxx:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp ]