apiVersion: v1
kind: Service
metadata:
  name: core
  namespace: {{ .Release.Namespace }}
  labels:
    app: core-agents
spec:
  clusterIP: None
  selector:
    app: core-agents
  ports:
    - name: grpc
      port: 50051
