apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest
  namespace: {{ .Release.Namespace }}
  labels:
    app: rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      imagePullSecrets:
        {{- include "base_pull_secrets" . }}
      initContainers:
        {{- include "base_init_containers" . }}
      containers:
        - name: rest
          resources: {{- .Values.rest.resources | toYaml | nindent 12 }}
          image: {{ .Values.mayastorCP.registry }}mayadata/mayastor-rest:{{ .Values.mayastorCP.tag }}
          imagePullPolicy: {{ .Values.mayastorCP.pullPolicy }}
          args:
            - "--dummy-certificates"
            - "--no-auth"
            - "--http=0.0.0.0:8081"
            - "--request-timeout={{ .Values.base.default_req_timeout }}"{{ if .Values.base.jaeger.enabled }}
            - "--jaeger={{ .Values.base.jaeger.agent.name }}:{{ .Values.base.jaeger.agent.port }}"{{ end }}
            - "--core-grpc=https://core:50051"
          ports:
            - containerPort: 8080
            - containerPort: 8081
          env:
            - name: RUST_LOG
              value: {{ .Values.mayastorCP.logLevel }}