apiVersion: v1
kind: Service
metadata:
  name: rest
  namespace: mayastor
  labels:
    app: rest
spec:
  type: NodePort
  selector:
    app: rest
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30010
