mayastorCP:
  tag: develop

base:
  jaeger:
    enabled: false

jaeger-operator:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: In
                values:
                  - ""
  tolerations:
    - key: node-role.kubernetes.io/master
