[package]
name = "agents"
version = "0.1.0"
authors = ["Tiago Castro <tiago.castro@mayadata.io>"]
edition = "2018"

[[bin]]
name = "core"
path = "core/src/server.rs"

[[bin]]
name = "jsongrpc"
path = "jsongrpc/src/server.rs"

[lib]
name = "common"
path = "common/src/lib.rs"

[dependencies]
nats = "0.8"
structopt = "0.3.15"
tokio = { version = "1", features = ["full"] }
tonic = "0.4"
futures = "0.3.8"
serde_json = "1.0"
async-trait = "=0.1.42"
dyn-clonable = "0.9.0"
smol = "1.0.0"
snafu = "0.6"
lazy_static = "1.4.0"
humantime = "2.0.1"
state = "0.4.2"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2.4"
rpc = "0.1.0"
http = "0.2.3"
paste = "1.0.4"
common-lib = { path = "../../common" }
reqwest = "0.11.4"
parking_lot = "0.11.1"
itertools = "0.10.0"

# todo: tracing
#opentelemetry-jaeger = { version = "0.14", features = ["tokio"] }
#tracing-opentelemetry = "0.14.0"
#opentelemetry = "0.15.0"

[dev-dependencies]
composer = { path = "../../composer" }
ctrlp-tests = { path = "../../tests/tests-mayastor" }
actix-rt = "2.2.0"
actix-web = { version = "4.0.0-beta.8", features = ["rustls"] }
url = "2.2.0"
once_cell = "1.4.1"

[dependencies.serde]
features = ["derive"]
version = "1.0"
