name: Submodule Branch Check
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  push:
    branches:
      - 'release/**'
      - staging
jobs:
  submodule-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check root submodules branch
        run: echo "Compat pass"

