name: "Release Artifacts"
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+**'
    branches:
      - 'release/**'

jobs:
  kubectl-plugin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        submodules: recursive
        fetch-depth: 0
    - run: |
        # BUG: HEAD tag is fetched as lightweight instead of annotated
        # https://github.com/actions/checkout/issues/290
        if [ "${{ github.ref_type }}" == "tag" ]; then
          git fetch -f origin ${{ github.ref }}:${{ github.ref }}
        fi
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos
    - run: nix-build -A utils.release.linux-musl.kubectl-plugin
    - uses: actions/upload-artifact@v2
      with:
        name: kubectl-mayastor-x86_64-linux-musl
        path: ./result/bin/kubectl-mayastor
    - run: nix-build -A utils.release.windows-gnu.kubectl-plugin
    - uses: actions/upload-artifact@v2
      with:
        name: kubectl-mayastor-x86_64-windows-gnu
        path: ./result/bin/kubectl-mayastor.exe
