name: Release Artifacts
on:
  push:
    branches:
      - 'release/**'

jobs:
  kubectl-plugin:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: linux-musl
          - os: macos-latest
            target: apple-darwin
          - os: ubuntu-latest
            target: windows-gnu
            suffix: .exe
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos
      - run: nix-build -A utils.release.${{ matrix.target }}.kubectl-plugin --arg incremental false
      - uses: actions/upload-artifact@v3
        with:
          name: kubectl-mayastor-${{ matrix.target }}
          path: ./result/bin/kubectl-mayastor${{ matrix.suffix }}
          if-no-files-found: error
