[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
tracing-opentelemetry = "0.21.0"
opentelemetry = { version = "0.20.0", features = ["rt-tokio-current-thread"] }
opentelemetry-jaeger = { version = "0.19.0", features = ["rt-tokio-current-thread"] }
version-info = { path = "../dependencies/version-info", default-features = false }
git-version-macro = { path = "../dependencies/git-version-macro" }
tracing = "0.1.37"
url = "2.4.1"
event-publisher = { path = "../dependencies/event-publisher" }
tracing-filter = { path = "../dependencies/tracing-filter" }
strum = "0.25.0"
strum_macros = "0.25.2"
heck = "0.4.1"